//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierCounter
    {
        public string CounterCode { get; set; }
        public string CounterName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Notes { get; set; }
        public string ShopId { get; set; }
    }
}
