//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpID { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string ShopID { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
