//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gold
    {
        public string GoldCode { get; set; }
        public string GoldName { get; set; }
        public string GoldType { get; set; }
        public Nullable<decimal> GoldAge { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
