//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldTransactionDetail
    {
        public System.Guid TransactionDetailId { get; set; }
        public Nullable<System.Guid> TransactionId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> TotalGoldWeight { get; set; }
        public string GoldCode { get; set; }
        public Nullable<decimal> GoldAge { get; set; }
        public Nullable<decimal> SellRate { get; set; }
        public Nullable<decimal> BuyRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> LineNumber { get; set; }
    }
}
