//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransactionDetail
    {
        public System.Guid TransactionDetailId { get; set; }
        public Nullable<System.Guid> TransactionId { get; set; }
        public string ProductCategoryId { get; set; }
        public string GoldCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UnitCode { get; set; }
        public string Notes { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
