//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string StockCode { get; set; }
        public string StockName { get; set; }
        public string ShopId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Address { get; set; }
    }
}
